### ISSUE TITLE
[Question] about `SNMPVariable` and `SNMPVariableList`

### ISSUE THREAD

**Issue by wangxin688** [carlkidcrypto/ezsnmp#141]
**What's on your mind?**
I'm very confused with `SNMPVariableList` in `variables.py`? is this object only a simple shortcut for `List[SNMPVariable]`?
`varbinds` method in class definition only return itself and it's inherited from list. 
how the varbinds work?

**Comment by carlkidcrypto** [comment]
The function doc string is self-explanatory. It represents of of these `netsnmp_variable_list` in the c/c++ code.

```
class SNMPVariableList(list):
    """
    An slight variation of a list which is used internally by the
    Net-SNMP C interface.
    """

    @property
    def varbinds(self):
        return self
```

**Comment by wangxin688** [comment]
> self-explanatory

thanks for elaborating this. I never write C or C++ before. so I not very clear with this.(only see pyi file before for c bind, haha)
