### ISSUE TITLE
[BUG] bulkwalk runs indefinitely when encountering a non-increasing OID

### ISSUE THREAD

**Issue by eoswald** [carlkidcrypto/ezsnmp#240]
**EzSNMP release version OR commit number**
1.1.0

**Operating System and Version**
- OS: Red Hat Enterprise Linux release
- Version 8.8 (Ootpa)

**Net-SNMP Library Version**
I think this is how to get it?
```
$ snmpbulkwalk --version
NET-SNMP version: 5.8
```

**Describe the bug**
I ran into this issue using `easysnmp` and decided to try this library too since it's actively being supported. I am running into this issue using `ezsnmp` too. You can find a detailed bug report here: https://github.com/easysnmp/easysnmp/issues/205

I'm not sure if the non-increasing OID is a red-herring but the few cases where I ran into this had that same problem.

**To Reproduce**
```
mkdir test_ezsnmp
cd test_ezsnmp
vim test_ezsnmp.py 
```
```python
import logging

from ezsnmp import Session


logging.basicConfig(level=logging.DEBUG)
session = Session(version=2, community="*****", security_username="*****", security_level="no_auth_or_privacy", auth_password="", context="", timeout=1.3, retries=0, hostname="X.X.X.X", use_sprint_value=True, use_numeric=True)
session.bulkwalk("1.0.8802.1.1.2.1.4.1.1.4", max_repetitions=10)
```
```
python3.9 -m venv venv  # also tested with python3.10
source ./venv/bin/activate
pip install ezsnmp==1.1.0
python test_ezsnmp.py
```

**Expected behavior**
I expect some kind of graceful failure or exit when OID are not increasing.

**Comment by carlkidcrypto** [comment]
thanks for reporting this bug.
Have you tried using this setting? and setting it to true? https://github.com/carlkidcrypto/ezsnmp/blob/mainline/1.x.x/ezsnmp/session.py#L175

**Comment by eoswald** [comment]
I just tried it and I get the same result. I'm not entirely sure how to read these logs but I think this is because the device is actually returning an OID that exists:
```
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
```

Maybe this means getnext is hitting an index that is referencing itself causing an infinite loop?

**Comment by carlkidcrypto** [comment]
Yeah, looks like the interface.cpp doesn't know how to handle a jump in the OIDs.

I think the netsnmp cml interface supports skipping OIDs via a flag. I'd have to look more into it.

I may just end up fixing this in v2.0.0.
In the next version I have reworked how we interact with the lower level netsnmp bindings.
Should be easier to extend support for the "allow non sequential OIDs" flag.

**Comment by eoswald** [comment]
> Yeah, looks like the interface.cpp doesn't know how to handle a jump in the OIDs.
> 
> I think the netsnmp cml interface supports skipping OIDs via a flag. I'd have to look more into it.

Yeah, they handle it outside the interface though:

https://github.com/net-snmp/net-snmp/blob/3c0642b00bb0ed6146a4fa453cb08badafaf1922/apps/snmpbulkwalk.c#L305-L318

https://github.com/net-snmp/net-snmp/blob/master/snmplib/snmp_api.c#L7015

**Comment by carlkidcrypto** [comment]
Update: I threw together a UT based on what you @eoswald shared. This is built of main and on this issues branch.

```
def test_snmp_bulkwalk_non_sequential_oids(netsnmp_args):
    
    if netsnmp_args[1] == "1":
        with pytest.raises(RuntimeError):
            netsnmp_args = netsnmp_args + ["1.0.8802.1.1.2.1.4.1.1.4"]
            snmpbulkwalk(netsnmp_args)
    else:
        netsnmp_args = netsnmp_args + ["1.0.8802.1.1.2.1.4.1.1.4"]
        res = snmpbulkwalk(netsnmp_args)
        
        for item in res:
            print(item.oid)
            print(item.index)
            print(item.value)
```

Here are the results
```
 tests/test_netsnmp.py ✓                                                                                             20% ██        iso.0.8802.1.1.2.1.4.1.1.4

No Such Object available on this agent at this OID
 tests/test_netsnmp.py ✓✓✓✓✓                                                                                        100% ██████████

Results (0.33s):
       5 passed
(python3.12.venv)
```

The code doesn't throw an exception. Is that something you'd like? If so, why?

**Comment by eoswald** [comment]
Nice, thank you! This seems reasonable to me, I don't think it's necessary to raise an exception.

**Comment by carlkidcrypto** [comment]
Is the OID `1.0.8802.1.1.2.1.4.1.1.4` a product-specific OID ? or is it a standard OID that is part of SNMPD?

**Comment by eoswald** [comment]
> Is the OID `1.0.8802.1.1.2.1.4.1.1.4` a product-specific OID ? or is it a standard OID that is part of SNMPD?

This is a standard IEEE OID that is supported by most of our vendors: https://www.ieee802.org/1/files/public/MIBs/LLDP-MIB-200505060000Z.mib

I am not sure if SNMPD packages it by default though since this is for devices with LLDP configured.

**Comment by carlkidcrypto** [comment]
I will be releasing V2.0.0a2 for you to test with @eoswald .
I'll post here once it is built and on PiPi.

**Comment by carlkidcrypto** [comment]
Done, https://github.com/carlkidcrypto/ezsnmp/releases/tag/v2.0.0a2 . It is highly experimental at this moment use with caution 👍🏽
