### ISSUE TITLE
[Question] move from easysnmp fails with Auth errors

### ISSUE THREAD

**Issue by johanreinalda** [carlkidcrypto/ezsnmp#96]
Trying to use ezsnmp, in an application that uses relies quite heavily on easysnmp.
By installing via "pip3 install ezsnmp", and replacing all occurances, I get errors for anything using snmp v3 with devices that work with easysnmp:

"File "/opt/openl2m/venv/lib/python3.11/site-packages/ezsnmp/session.py", line 478, in bulkwalk
    interface.bulkwalk(self, non_repeaters, max_repetitions, varlist)
ezsnmp.exceptions.EzSNMPError: Authentication failure (incorrect password, community or key)
"

Environment:
Ubuntu 22.04.4, fully patched, with Net-Snmp 5.9.1

Even a simple script fails. If using easysnmp, both v2c and v3 work, if using ezsnmp.Session(), v3 fails.

What am I missing ?

Johan

-------------------------------------
import ezsnmp
import easysnmp

system = ".1.3.6.1.2.1.1"

snmpv2 = ezsnmp.Session(
                hostname="10.1.1.1",
                version=2,
                community="read_only",
        )

items = snmpv2.bulkwalk(oids=system)
for item in items:
    print(f"Found: {item}")

snmpv3 = ezsnmp.Session(
                hostname="10.1.1.1",
                version=3,
                security_level=u"auth_without_privacy",
                security_username=u"view",
                auth_protocol=u"SHA",
                auth_password=u"password",
        )

items = snmpv3.bulkwalk(oids=system)
for item in items:
    print(f"Found: {item}")

**Comment by carlkidcrypto** [comment]
@johanreinalda thanks for opening up this question.
Do you know what version of open ssl you are using ?

**Comment by johanreinalda** [comment]
Yes, it is:

openssl/jammy-updates,jammy-security,now 3.0.2-0ubuntu1.15

**Comment by johanreinalda** [comment]
I just ran this on an Ubuntu 20.04 system with
openssl/focal-updates,focal-security,now 1.1.1f-1ubuntu2.22 amd64 [installed,automatic]

Same erors.

I built a quick Python3.11 virtual environment, with 'wheel' and 'setuptools'. Then installed both easysnmp and ezsnmp.  I noticed a difference between the install of ezsnmp and easysnmp, using pip. Easysnmp builds a package, ezsnmp does not...

See build output below.


(venv) reinaldj@noctools3:/opt/test$ pip3 install --upgrade wheel setuptools
Collecting wheel
  Downloading wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: setuptools in ./venv/lib/python3.11/site-packages (65.5.0)
Collecting setuptools
  Downloading setuptools-70.0.0-py3-none-any.whl.metadata (5.9 kB)
Downloading wheel-0.43.0-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 kB 1.9 MB/s eta 0:00:00
Downloading setuptools-70.0.0-py3-none-any.whl (863 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 863.4/863.4 kB 14.0 MB/s eta 0:00:00
Installing collected packages: wheel, setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 65.5.0
    Uninstalling setuptools-65.5.0:
      Successfully uninstalled setuptools-65.5.0
Successfully installed setuptools-70.0.0 wheel-0.43.0



(venv) reinaldj@noctools3:/opt/test$ pip3 install ezsnmp
Collecting ezsnmp
  Downloading ezsnmp-1.0.0rc1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.0 kB)
Downloading ezsnmp-1.0.0rc1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 20.5 MB/s eta 0:00:00
Installing collected packages: ezsnmp
Successfully installed ezsnmp-1.0.0rc1


(venv) reinaldj@noctools3:/opt/test$ pip3 install easysnmp
Collecting easysnmp
  Downloading easysnmp-0.2.6.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.0/43.0 kB 1.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: easysnmp
  Building wheel for easysnmp (setup.py) ... done
  Created wheel for easysnmp: filename=easysnmp-0.2.6-cp311-cp311-linux_x86_64.whl size=109442 sha256=63a2c79ce2898f9fece595df7c969a198e11f69dd79a91e72e1da43a90984e02
  Stored in directory: /home/reinaldj/.cache/pip/wheels/24/f7/9e/17165dfe16ee7efbbfd11a8689b55f3f0c250d2cf4c3d57d3e
Successfully built easysnmp
Installing collected packages: easysnmp
Successfully installed easysnmp-0.2.6

**Comment by carlkidcrypto** [comment]
Yes, that's correct. Ezsnmp builds many wheels to support as many Linux distros. 
 This is the project we use to do that.

https://cibuildwheel.pypa.io/en/stable/

You can always install it from the source and see if that makes a difference.

...

On a different note, I wonder if older authentication methods like SHA aren't supported in the latest versions of net-snmp. This requires some extra research.

**Comment by carlkidcrypto** [comment]
@johanreinalda I found the issue. https://github.com/carlkidcrypto/ezsnmp/blob/main/ezsnmp/interface.cpp#L96-L106
The current way things are compiled includes in MD5, but not SHA.
I am tempted to remove those nested ifdef blocks, but that may open up more issues.

**Comment by johanreinalda** [comment]
it's been decades since i did C code, but as I read that, in both cases of NETSNMP_DISABLE_MD5 I think the "SHA" algo is included ? (code appears identical to easysnmp).

**Comment by carlkidcrypto** [comment]
@johanreinalda  I've been doing some digging. It looks like EasySNMP the original project this fork is based on has a similar issue. https://github.com/easysnmp/easysnmp/issues/199

For them doing something like this `pip install --force-reinstall --no-binary :all: ezsnmp` worked.

**Comment by carlkidcrypto** [comment]
@johanreinalda  try this version of the script you provided. I removed the `u` from the strings.

```python3
import easysnmp

system = ".1.3.6.1.2.1.1"

snmpv2 = ezsnmp.Session(
hostname="10.1.1.1",
version=2,
community="read_only",
)

items = snmpv2.bulkwalk(oids=system)
for item in items:
print(f"Found: {item}")

snmpv3 = ezsnmp.Session(
hostname="10.1.1.1",
version=3,
security_level="auth_without_privacy",
security_username="view",
auth_protocol="SHA",
auth_password="password",
)

items = snmpv3.bulkwalk(oids=system)
for item in items:
print(f"Found: {item}")
```

**Comment by johanreinalda** [comment]
I ran the "pip force" and this now works, with or withouth the Unicode strings for passphrase, etc.

Thanks for your work on this, much appreciated!
